from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pref_editor(object):
    def setupUi(self, pref_editor):
        pref_editor.setObjectName("pref_editor")
        pref_editor.resize(381, 353)
        pref_editor.setAccessibleName("")
        self.min_slider = QtWidgets.QSlider(pref_editor)
        self.min_slider.setGeometry(QtCore.QRect(110, 180, 160, 22))
        self.min_slider.setMinimum(-60)
        self.min_slider.setMaximum(140)
        self.min_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_slider.setObjectName("min_slider")
        self.min_label = QtWidgets.QLabel(pref_editor)
        self.min_label.setGeometry(QtCore.QRect(40, 180, 61, 20))
        self.min_label.setObjectName("min_label")
        self.category_dropdown = QtWidgets.QComboBox(pref_editor)
        self.category_dropdown.setGeometry(QtCore.QRect(140, 70, 131, 22))
        self.category_dropdown.setObjectName("category_dropdown")
        self.category_dropdown.addItem("")
        self.category_dropdown.addItem("")
        self.category_dropdown.addItem("")
        self.category_dropdown.addItem("")
        self.category_dropdown.addItem("")
        self.sec_cond_button = QtWidgets.QPushButton(pref_editor)
        self.sec_cond_button.setGeometry(QtCore.QRect(100, 30, 171, 28))
        self.sec_cond_button.setObjectName("sec_cond_button")
        self.max_label = QtWidgets.QLabel(pref_editor)
        self.max_label.setGeometry(QtCore.QRect(40, 250, 61, 20))
        self.max_label.setObjectName("max_label")
        self.factor_dropdown = QtWidgets.QComboBox(pref_editor)
        self.factor_dropdown.setGeometry(QtCore.QRect(140, 100, 131, 22))
        self.factor_dropdown.setObjectName("factor_dropdown")
        self.factor_dropdown.addItem("")
        self.factor_dropdown.addItem("")
        self.factor_dropdown.addItem("")
        self.factor_dropdown.addItem("")
        self.factor_dropdown.addItem("")
        self.factor_dropdown.addItem("")
        self.min_highest_label = QtWidgets.QLabel(pref_editor)
        self.min_highest_label.setGeometry(QtCore.QRect(260, 200, 31, 16))
        self.min_highest_label.setObjectName("min_highest_label")
        self.max_spin_box = QtWidgets.QDoubleSpinBox(pref_editor)
        self.max_spin_box.setGeometry(QtCore.QRect(290, 250, 62, 22))
        self.max_spin_box.setObjectName("max_spin_box")
        self.add_button = QtWidgets.QPushButton(pref_editor)
        self.add_button.setGeometry(QtCore.QRect(100, 300, 71, 28))
        self.add_button.setObjectName("add_button")
        self.category_label = QtWidgets.QLabel(pref_editor)
        self.category_label.setGeometry(QtCore.QRect(80, 70, 55, 16))
        self.category_label.setObjectName("category_label")
        self.factor_label = QtWidgets.QLabel(pref_editor)
        self.factor_label.setGeometry(QtCore.QRect(90, 100, 55, 16))
        self.factor_label.setObjectName("factor_label")
        self.min_lowest_label = QtWidgets.QLabel(pref_editor)
        self.min_lowest_label.setGeometry(QtCore.QRect(110, 200, 31, 16))
        self.min_lowest_label.setObjectName("min_lowest_label")
        self.min_spin_box = QtWidgets.QDoubleSpinBox(pref_editor)
        self.min_spin_box.setGeometry(QtCore.QRect(290, 180, 62, 22))
        self.min_spin_box.setObjectName("min_spin_box")
        self.cancel_button = QtWidgets.QPushButton(pref_editor)
        self.cancel_button.setGeometry(QtCore.QRect(200, 300, 71, 28))
        self.cancel_button.setObjectName("cancel_button")
        self.label = QtWidgets.QLabel(pref_editor)
        self.label.setGeometry(QtCore.QRect(100, 130, 31, 16))
        self.label.setObjectName("label")
        self.comboBox_3 = QtWidgets.QComboBox(pref_editor)
        self.comboBox_3.setGeometry(QtCore.QRect(140, 130, 51, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.max_slider = QtWidgets.QSlider(pref_editor)
        self.max_slider.setGeometry(QtCore.QRect(110, 240, 160, 22))
        self.max_slider.setMinimum(-60)
        self.max_slider.setMaximum(140)
        self.max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_slider.setObjectName("max_slider")
        self.max_highest_label = QtWidgets.QLabel(pref_editor)
        self.max_highest_label.setGeometry(QtCore.QRect(260, 260, 31, 16))
        self.max_highest_label.setObjectName("max_highest_label")
        self.max_lowest_label = QtWidgets.QLabel(pref_editor)
        self.max_lowest_label.setGeometry(QtCore.QRect(110, 260, 31, 16))
        self.max_lowest_label.setObjectName("max_lowest_label")

        self.retranslateUi(pref_editor)
        QtCore.QMetaObject.connectSlotsByName(pref_editor)

    def retranslateUi(self, pref_editor):
        _translate = QtCore.QCoreApplication.translate
        pref_editor.setWindowTitle(_translate("pref_editor", "Edit Preference"))
        self.min_label.setText(_translate("pref_editor", "Minimum"))
        self.category_dropdown.setItemText(0, _translate("pref_editor", "-"))
        self.category_dropdown.setItemText(1, _translate("pref_editor", "Perfect"))
        self.category_dropdown.setItemText(2, _translate("pref_editor", "Good"))
        self.category_dropdown.setItemText(3, _translate("pref_editor", "Bad"))
        self.category_dropdown.setItemText(4, _translate("pref_editor", "Terrible"))
        self.sec_cond_button.setText(_translate("pref_editor", "Add Secondary Condition"))
        self.max_label.setText(_translate("pref_editor", "Maximum"))
        self.factor_dropdown.setItemText(0, _translate("pref_editor", "High Temperature"))
        self.factor_dropdown.setItemText(1, _translate("pref_editor", "Low Temperature"))
        self.factor_dropdown.setItemText(2, _translate("pref_editor", "Rain Level"))
        self.factor_dropdown.setItemText(3, _translate("pref_editor", "Snow Level"))
        self.factor_dropdown.setItemText(4, _translate("pref_editor", "Mixed Precipitation Level"))
        self.factor_dropdown.setItemText(5, _translate("pref_editor", "Wind Speed"))
        self.min_highest_label.setText(_translate("pref_editor", "120"))
        self.add_button.setText(_translate("pref_editor", "Add"))
        self.category_label.setText(_translate("pref_editor", "Category"))
        self.factor_label.setText(_translate("pref_editor", "Factor"))
        self.min_lowest_label.setText(_translate("pref_editor", "-50"))
        self.cancel_button.setText(_translate("pref_editor", "Cancel"))
        self.label.setText(_translate("pref_editor", "Rank"))
        self.comboBox_3.setItemText(0, _translate("pref_editor", "-"))
        self.max_highest_label.setText(_translate("pref_editor", "120"))
        self.max_lowest_label.setText(_translate("pref_editor", "-50"))
